apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: submission-events-notification-service
  description: Submission Events Notification Service is a Service based on Java and Spring AOP.
  tags:
    - java
spec:
  type: service
  owner: guests
  lifecycle: production
  providesApis:
    - account-service-example
  consumesApis:
    - example-grpc-api
