apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
 name: atm-locator
 description: ATM locator search application
 tags:
   - tanzu
spec:
  type: service
  lifecycle: experimental
  owner: default-team
  system: atm-locator
  providesApis:
    - atm-locator