apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: submission-events-notification-service
  description: Submission Events Notification Service is a Service based on Java and Spring AOP.
  tags:
    - java
spec:
  type: service
  owner: guests
  lifecycle: production
  providesApis:
    - sens-api
  consumesApis:
    - example-grpc-api
  dependsOn:
    - secret-manager
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sens-api
  description: Submission events notification service that receives event notifications from underlying peer review systems such as Editorial Manager (EM) and ScholarOne (S1).
spec:
  type: openapi
  lifecycle: production
  owner: guests
  definition: 
    $text: https://github.com/monikajayaram/test-backstage/blob/main/swagger.json
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: secret-manager
  description: Get secret values
spec:
  type: aws-secret-manager
  owner: guests
