apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: submission-events-notification-service
  description: Submission Events Notification Service is a Service based on Java and Spring AOP.
  annotations:
    github.com/project-slug: tandfgroup/submission-events-notification-service
    tags:
      - java
spec:
  type: service
  owner: OA
  lifecycle: production
  providesApis:
    - health
    - S1M Update Status
    - EM ingest status
    - EM update status
    - S1M invite stub
    - S1M invite author
  consumesApis:
    - mms
  dependsOn:
    - component:ft-metadata-management-service
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: mms
  description: Metadata Management Service is an API Service based on Java, Spring Boot.
spec:
    type: openapi
    owner: OA
    lifecycle: production
    definition: |
      openapi: "3.0.0"
      info:
        version: 1.0.0
        title: MMS API
      paths:
        /health:
          get:
            summary: health check
    apiConsumedBy:
      - submission-events-notification-service