apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: submission-events-notification-service
  description: Submission Events Notification Service is a Service based on Java and Spring AOP.
spec:
  type: service
  owner: OA
  lifecycle: production
  providesApis:
    - health
    - S1M Update Status
    - EM ingest status
    - EM update status
    - S1M invite stub
    - S1M invite author
  consumesApis:
    - mms
  dependsOn:
    - website:example-website
